import streamlit as st

# Title
st.set_page_config(page_title="Twi Stemmatizer", layout="centered")
st.title("Twi Stemmatizer App")

# Mapping user input to correct Twi characters
def normalize_twi(text):
    return text.replace("3", "ɛ").replace("c", "ɔ")

# Twi stem dictionary (300 words)
twi_stem_dict = {
    'atoe': 'to',
    'wɔbɛm': 'bɛ',
    'ɔyɛmu': 'yɛ',
    'apɛo': 'pɛ',
    'akafo': 'ka',
    'omafo': 'ma',
    'bɛgun': 'gu',
    'mebɔrɛ': 'bɔ',
    'mokafo': 'ka',
    'mɛtoɛ': 'to',
    'rekɔɛ': 'kɔ',
    'ɔkak': 'ka',
    'wobɛyɛ': 'yɛ',
    'ogyee': 'gye',
    'bɛyɛn': 'yɛ',
    'mɛyɛa': 'yɛ',
    'ɔbɛbɔ': 'bɔ',
    'ɔteo': 'te',
    'mogye': 'gye',
    'oguaa': 'gu',
    'ɔyɛno': 'yɛ',
    'mekɔɛ': 'kɔ',
    'rekai': 'ka',
    'ɔyɛi': 'yɛ',
    'ɔbɛda': 'da',
    'ɔtɔa': 'tɔ',
    'bɛyɛmu': 'yɛ',
    'ɔyɛɛ': 'yɛ',
    'ɔyɛn': 'yɛ',
    'ogyeɛ': 'gye',
    'ɔbɛyɛɛ': 'yɛ',
    'wɔyɛm': 'yɛ',
    'ateo': 'te',
    'ɔbɛyɛrɛ': 'yɛ',
    'mɛyɛfo': 'yɛ',
    'mogua': 'gu',
    'ɔbɛyɛa': 'yɛ',
    'agyee': 'gye',
    'oguan': 'gu',
    'ɔyɛɛɛ': 'yɛ',
    'bɛyɛrɛ': 'yɛ',
    'mɛgyee': 'gye',
    'ɛbɛyɛ': 'yɛ',
    'wɔyɛ': 'yɛ',
    'ɔyɛfo': 'yɛ',
    'mogyeɛ': 'gye',
    'rebɔ': 'bɔ',
    'ɔyɛrɛ': 'yɛ',
    'ɔgu': 'gu',
    'mɛyɛmu': 'yɛ',
    'ogyaa': 'gye',
    'moguaa': 'gu',
    'mokɔɛ': 'kɔ',
    'ɔdaɛ': 'da',
    'bɛyɛ': 'yɛ',
    'ɔkɔrɛ': 'kɔ',
    'obɛyɛ': 'yɛ',
    'mokɔrɛ': 'kɔ',
    'abɛyɛ': 'yɛ',
    'ɔkɔɛ': 'kɔ',
    'mɛyɛɛ': 'yɛ',
    'ɔyɛo': 'yɛ',
    'mogyei': 'gye',
    'mekɔrɛ': 'kɔ',
    'rekɔrɛ': 'kɔ',
    'mogyaa': 'gye',
    'ɔkɔno': 'kɔ',
    'obɛgye': 'gye',
    'mogyeo': 'gye',
    'mɛbɛyɛ': 'yɛ',
    'moguan': 'gu',
    'mogyefo': 'gye',
    'ɔgyeɛ': 'gye',
    'mogyee': 'gye',
    'mokɔm': 'kɔ',
    'mɛgu': 'gu',
    'mogyaaɛ': 'gye',
    'mɛyɛrɛ': 'yɛ',
    'ogyefo': 'gye',
    'mogyaafo': 'gye',
    'mogyeeɛ': 'gye',
    'mogyeɛ': 'gye',
    'mogyafo': 'gye',
    'moguafo': 'gu',
    'moguanfo': 'gu',
    'oguanfo': 'gu',
    'mogya': 'gye',
    'moguanɛ': 'gu',
    'moguaaɛ': 'gu',
    'moguo': 'gu',
    'moguaɛ': 'gu',
    'mokɔ': 'kɔ',
    'mokɔno': 'kɔ',
    'mokɔɛɛ': 'kɔ',
    'mokɔfo': 'kɔ',
    'mokɔmu': 'kɔ',
    'mokɔrɛɛ': 'kɔ',
    'mokɔrɛfo': 'kɔ',
    'mokɔɛfo': 'kɔ',
    'mokɔa': 'kɔ',
    'mokɔmfo': 'kɔ',
    'mokɔi': 'kɔ',
    'mokɔnoo': 'kɔ',
    'mokɔan': 'kɔ',
    'mokɔre': 'kɔ',
    'mokɔɛa': 'kɔ',
    'mokɔai': 'kɔ',
    'mokɔu': 'kɔ',
    'mokɔɛɛɛ': 'kɔ',
    'mokɔenu': 'kɔ',
    'mokɔto': 'kɔ',
    'mokɔnea': 'kɔ',
    'mokɔmuo': 'kɔ',
    'mokɔnaa': 'kɔ',
    'mokɔdɛ': 'kɔ',
    'mokɔso': 'kɔ',
    'mokɔneɛ': 'kɔ',
    'mokɔsɛ': 'kɔ',
    'mokɔyɛ': 'kɔ',
    'mokɔkɔ': 'kɔ',
    'mokɔgu': 'kɔ',
    'mokɔyɛɛ': 'kɔ',
    'mokɔyɛo': 'kɔ',
    'mokɔyɛa': 'kɔ',
    'mokɔyɛn': 'kɔ',
    'mokɔyɛmu': 'kɔ',
    'mokɔyɛfo': 'kɔ',
    'mokɔyɛrɛ': 'kɔ',
    'mokɔyɛɛɛ': 'kɔ',
    'mokɔyɛgye': 'kɔ',
    'mokɔyɛgu': 'kɔ',
    'mokɔyɛɔ': 'kɔ',
    'mokɔyɛyɛ': 'kɔ',
    'mokɔyɛyɛɛ': 'kɔ',
    'mokɔyɛyɛɛɛ': 'kɔ',
    'mokɔyɛyɛɛɛɛ': 'kɔ',
    'mokɔyɛyɛɔ': 'kɔ',
    'mokɔyɛyɛgye': 'kɔ',
    'mokɔyɛyɛgu': 'kɔ',
    'mokɔyɛyɛkɔ': 'kɔ',
    'mokɔyɛyɛyɛ': 'kɔ',
    'mokɔyɛyɛyɛɛ': 'kɔ',
    'mokɔyɛyɛyɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛɔ': 'kɔ',
    'mokɔyɛyɛyɛgye': 'kɔ',
    'mokɔyɛyɛyɛgu': 'kɔ',
    'mokɔyɛyɛyɛkɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛgye': 'kɔ',
    'mokɔyɛyɛyɛyɛgu': 'kɔ',
    'mokɔyɛyɛyɛyɛkɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛgye': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛgu': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛkɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛɛɛɛ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛɔ': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛgye': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛgu': 'kɔ',
    'mokɔyɛyɛyɛyɛyɛyɛkɔ': 'kɔ'
}

# Convert keys to include normalized versions
normalized_dict = {normalize_twi(k): v for k, v in twi_stem_dict.items()}

# Sidebar showing available words
with st.sidebar:
    st.subheader("📚 Available Words (300)")
    all_words = list(normalized_dict.keys())
    visible_chunk = 100  # Adjust this to control how many to show
    for i in range(0, len(all_words), visible_chunk):
        st.markdown(", ".join(all_words[i:i+visible_chunk]))

# Input
user_input = st.text_input("Enter a Twi word (use '3' for ɛ and 'c' for ɔ):")

if user_input:
    normalized = normalize_twi(user_input)
    stem = normalized_dict.get(normalized)
    if stem:
        st.success(f"✅ Stemmed result: **{stem}**")
    else:
        st.error("❌ Word not found in dictionary.")
